module.exports = {
	'env': {
		'node': true,
		'es6': true,
		'jest': true,
	},
	'parserOptions': {
		'sourceType': 'module',
	},
	'plugins': [
		'import',
		'promise',
		'lodash',
	],
	'settings': {
		'import/extensions': ['js'],
	},
	'rules': {
		'import/default': 2,
		'import/export': 2,
		'import/imports-first': 2,
		'import/named': 2,
		'import/namespace': 2,
		'import/newline-after-import': 2,
		'import/no-extraneous-dependencies': 2,
		'import/no-mutable-exports': 2,
		'import/no-named-as-default-member': 2,
		'import/no-named-as-default': 2,
		'import/no-unresolved': [2, { 'commonjs': true }],
		'import/prefer-default-export': 0,
		'lodash/chaining': 0,
		'promise/always-return': 2,
		'promise/catch-or-return': 2,
		'promise/no-native': 0,
		'promise/param-names': 2,
		'arrow-parens': [2, 'always'],
		'arrow-spacing': [2, { 'before': true,	'after': true }],
		'comma-dangle': [2, 'always-multiline'],
		'comma-spacing': 2,
		'constructor-super': 2,
		'eol-last': 2,
		'indent': ['error', 'tab'],
		'key-spacing': [2, { 'mode': 'minimum' }],
		'keyword-spacing': 2,
		'new-parens': 2,
		'no-class-assign': 2,
		'no-confusing-arrow': [2, { 'allowParens': true }],
		'no-console': 2,
		'no-const-assign': 2,
		'no-control-regex': 2,
		'no-debugger': 2,
		'no-delete-var': 2,
		'no-dupe-args': 2,
		'no-dupe-class-members': 2,
		'no-dupe-keys': 2,
		'no-duplicate-case': 2,
		'no-else-return': 2,
		'no-empty-character-class': 2,
		'no-ex-assign': 2,
		'no-extra-boolean-cast': 2,
		'no-extra-parens': [2, 'functions'],
		'no-extra-semi': 2,
		'no-fallthrough': 2,
		'no-func-assign': 2,
		'no-invalid-regexp': 2,
		'no-irregular-whitespace': 2,
		'no-mixed-requires': 2,
		'no-mixed-spaces-and-tabs': 2,
		'no-multiple-empty-lines': [2, { 'max': 2 }],
		'no-negated-in-lhs': 2,
		'no-new-require': 2,
		'no-new-symbol': 2,
		'no-obj-calls': 2,
		'no-octal': 2,
		'no-path-concat': 2,
		'no-proto': 2,
		'no-redeclare': 2,
		'no-restricted-modules': [2, 'sys', '_linklist'],
		'no-self-assign': 2,
		'no-this-before-super': 2,
		'no-trailing-spaces': 2,
		'no-undef': 2,
		'no-unexpected-multiline': 2,
		'no-unreachable': 2,
		'no-unused-labels': 2,
		'no-unused-vars': [2, { 'args': 'none' }],
		'prefer-const': 2,
		'quotes': [2, 'single', { 'allowTemplateLiterals': true }],
		'semi': 2,
		'space-before-blocks': [2, 'always'],
		'space-before-function-paren': [2, 'never'],
		'space-in-parens': [2, 'never'],
		'space-infix-ops': 2,
		'space-unary-ops': 2,
		'template-curly-spacing': 2,
		'use-isnan': 2,
		'valid-typeof': 2,
	},
};
